/**:
  ros__parameters:
    ip_address: "10.0.0.151"
    port: 16171
    frame_id: "dvl_link"
    twist_topic: "/orca/twist"
    pose_topic: "/orca/pose"
    altitude_topic: "/dvl/altitude"
    transducer_array_topic: "/dvl/transducer_array"
    publish_transducer_array: true
