ros_dvl_a50_driver_node:
  ros__parameters:
    ip_address: "192.168.194.95"
    port: 16171
    frame_id: "dvl_link"
    twist_topic: "/orca/twist"
    pose_topic: "/orca/pose"
    depth_topic: "/dvl/depth"
